[package]
name = "Red-Blue-pixel-and-Yellow-Pixel-pixel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
